provider_manager/provider_manager/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', admin.site.urls),
    path('sales/', include('sales.urls')),
    path('collections/', include('inventory.urls')),
    path('providers/', include('provider.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('invoicing/', include('invoicing.urls')),
]

provider_manager/sales/urls.py
from django.urls import path
from sales.views import (
    OrderDetailView, pdfReportSales, ShopingCartView,
    SearchSalesByMonthView
)


urlpatterns = [
    path('invoice/<int:pk>', OrderDetailView.as_view(), name='invoice-detail'),
    path('cart/', ShopingCartView.as_view(), name="cart"),
    path('report/pdf', pdfReportSales, name='report-sales'),
    path('search/', SearchSalesByMonthView.as_view(), name="search-month"),
]

provider_manager/payments/models.py
from django.db import models
from django.urls import reverse
from decimal import Decimal

from django.contrib.auth.models import User
from django.db.models import Sum

from sales.models import Order, Utility
from provider.models import Bill
from sales.models import OrderDetailSale

# Create your models here.
set_way_to_pay = (
    ('e','efectivo'),
    ('n','nequi'),
    ('b','bancolombia'),
    ('bb','banco bogota'),
    ('bcs','caja social'),
    ('bd','davivienda'),
)

class Provider(models.Model):
    reference = models.CharField(("referencia"), max_length=50, unique=True)
    user = models.ForeignKey(User, verbose_name=("user"), on_delete=models.CASCADE)
    bill = models.ForeignKey(Bill, verbose_name=("bills"), on_delete=models.CASCADE)
    value = models.DecimalField(("valor"), max_digits=10, decimal_places=2, default=0.0)
    description = models.TextField(("descripcion"), max_length=50, null=True, blank=True)
    createdAt = models.DateField(("fecha"), auto_now=False)

    class Meta:
        verbose_name = ("Provider")
        verbose_name_plural = ("Providers")
        ordering = ("-createdAt",)

    def __str__(self):
        return self.bill.number

    def get_absolute_url(self):
        return reverse("Provider_detail", kwargs={"pk": self.pk})
    
    def save(self, *args, **kwargs):
        is_paid = False
        bill = Bill.objects.get(id=self.bill.id)
        
        if (bill.total - self.value) == 0:
            is_paid = True
        else:
            res_value = bill.total - (self.total_pays() + self.value)

            if res_value <= 100:
                is_paid = True
        
        if is_paid:
            bill.is_paid = is_paid
            bill.save()
        return super().save(*args, **kwargs)
    
    def total_balance(self):
        total = 0
        payments = Provider.objects.filter(bill=self.bill.id)
        if payments:
            total = payments.aggregate(Sum('value'))['value__sum']
        return total
    
    def total_pays(self):
        total = 0
        query = Provider.objects.filter(bill=self.bill.id).aggregate(Sum('value'))
        if query["value__sum"] != None:
          total = query["value__sum"]
        return total

class SalesBill(models.Model):
    order = models.ForeignKey(Order, verbose_name=("orders"), on_delete=models.CASCADE)
    total = models.DecimalField(("value"), max_digits=10, decimal_places=2, default=0.0)
    way_to_pay = models.CharField(("tipo pago"), max_length=10, choices=set_way_to_pay, default=set_way_to_pay[0])
    createdAt = models.DateField(("creado"), auto_now_add=False)

    class Meta:
        verbose_name = ("SalesBill")
        verbose_name_plural = ("SalesBills")
        ordering = ("-createdAt",)

    def __str__(self):
        return self.order.number

    def get_absolute_url(self):
        return reverse("Bill_detail", kwargs={"pk": self.pk})

    def save(self, *args, **kwargs):
        order_details = OrderDetailSale.objects.filter(order=self.order)
        print(order_details)
        
        for item in order_details:
            value_ = item.total - (item.product.cost_with_tax * item.amount)
            util = Utility(orderdetail_id=item.id, value=value_, createdAt=self.order.createdAt)
            util.save()
        
        return super().save(*args, **kwargs)

provider_manager/sales/models.py
from django.db import models
from django.urls import reverse
from inventory.models import Product
from django.contrib.auth.models import User
from decimal import Decimal
from django.db.models import Count, Sum

# Create your models here.
class Client(models.Model):
    name = models.CharField(("nombres"), max_length=150)
    num_doc = models.CharField(("cedula"), max_length=20, blank=True, null=True)
    address = models.CharField(("direccion"), max_length=50, blank=True, null=True)
    phone = models.CharField(("telefono"), max_length=50, blank=True, null=True)
    
    class Meta:
        verbose_name = ("Client")
        verbose_name_plural = ("Clients")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("Client_detail", kwargs={"pk": self.pk})

class OrderDetailSale(models.Model):
    product = models.ForeignKey(Product, verbose_name=("products"), on_delete=models.CASCADE)
    amount = models.IntegerField(("cantidad"), default=0)
    price = models.DecimalField(("precio"), max_digits=10, decimal_places=2, default=0.0)
    dto = models.DecimalField(("descuento"), max_digits=10, decimal_places=2, default=0.0)
    total = models.DecimalField(("total"), max_digits=10, decimal_places=2, default=0.0)
    
    class Meta:
        verbose_name = ("OrderDetail")
        verbose_name_plural = ("OrderDetails")

    def __str__(self):
        return self.product.description

    def get_absolute_url(self):
        return reverse("OrderDetail_detail", kwargs={"pk": self.pk})

    def save(self, *args, **kwargs):
        self.total = (self.amount * self.price ) - self.dto    
        return super().save(*args, **kwargs)
    
class Order(models.Model):
    user = models.ForeignKey(User, verbose_name=("vendedor"), on_delete=models.CASCADE)
    client = models.ForeignKey(Client, verbose_name=("clients"), on_delete=models.CASCADE)
    number = models.CharField(("factura"), max_length=50, unique=True)
    orderdetails = models.ManyToManyField(OrderDetailSale, verbose_name=("orderdetailsales"))
    subtotal = models.DecimalField(("subtotal"), max_digits=10, decimal_places=2, default=0.0)
    tax = models.DecimalField(("impuesto"), max_digits=10, decimal_places=2, default=0.0)
    total = models.DecimalField(("total"), max_digits=10, decimal_places=2, default=0.0)
    coments = models.TextField(("observaciones"), blank=True, null=True)
    is_paid = models.BooleanField(("cancelado"), default=False)
    createdAt = models.DateField(("fecha"), auto_now=False)

    class Meta:
        verbose_name = ("Order")
        verbose_name_plural = ("Orders")
        ordering = ("-createdAt",)

    def __str__(self):
        return self.number

    def get_absolute_url(self):
        return reverse("Order_detail", kwargs={"pk": self.pk})
    
    def set_number_bill():
        return f'{4090 + Order.objects.all().count()}'

    def save(self, *args, **kwargs):
        items = OrderDetailSale.objects.filter(order__createdAt=self.createdAt).filter(order__id=self.id)
        print(items)
        if items:
            print(items.filter(order__id=self.id))
            total = items.aggregate(Sum('total'))
            self.total = total['total__sum']
            self.subtotal = self.total / Decimal(1.19)
            self.tax = self.total - self.subtotal
            
        return super().save(*args, **kwargs)


class Utility(models.Model):
    orderdetail = models.ForeignKey(OrderDetailSale, verbose_name=("orderdetailsales"), on_delete=models.CASCADE)
    value = models.DecimalField(("valor"), max_digits=10, decimal_places=2, default=0.0)
    createdAt = models.DateField(auto_now_add=False, blank=True, null=True)
    
    class Meta:
        verbose_name = ("Utility")
        verbose_name_plural = ("Utilities")
        ordering = ("-createdAt",)

    def __str__(self):
        return f'{self.orderdetail}'

    def get_absolute_url(self):
        return reverse("Utility_detail", kwargs={"pk": self.pk})

provider_manager/sales/forms.py
from django import forms
from sales.models import Order, Client, OrderDetailSale
from django.contrib.auth.models import User

def get_sellerman():
    return User.objects.first().username

def set_number_order():
    num_order = Order.objects.all().count()
    return f'{num_order + 4090}'

def get_bill_not_cancel():
    choices = (('Option 1', 'Option 1'),('Option 2', 'Option 2'),)
    order = Order.objects.filter(is_paid=False)[0]
    choices = ((order.id, order),)
    return choices
    
class OrderForm(forms.ModelForm):
    number = forms.CharField(initial=set_number_order)
    
    class Meta:
        model = Order
        fields = ("user","client","number","orderdetails","createdAt","total","coments")
        # exclude = ("user","client","createdAt","total","coments")

class ClientForm(forms.ModelForm):
    num_doc = forms.CharField(initial='22222222')
    address = forms.CharField(initial='no aplica')
    phone = forms.CharField(initial='000-000-0000')
    
    class Meta:
        model = Client
        fields = ("name","num_doc","address","phone")

class OrderDetailSaleForm(forms.ModelForm):
    class Meta:
        model = OrderDetailSale
        fields = ("product","amount","price","dto")

        widgets = {
            "product": forms.Select(attrs={"class":"form-select form-select-sm"}),
        }

provider_manager/sales/views.py
from django.shortcuts import render
from django.db.models import Q

from sales.models import Order, Client, OrderDetailSale
from inventory.models import Product, Category

from django.views.generic import TemplateView
from django.views.generic import CreateView
from django.views.generic import DetailView
from django.views.generic import ListView

from datetime import datetime
from django.db.models import Sum
from django.http import JsonResponse

from sales.forms import OrderDetailSaleForm

from reportlab.pdfgen import canvas
from django.http import HttpResponse

# Create your views here.

#view para filtrar  clientes por su nombre
def SearchClientListView(request):
    query = request.GET.get('q')
    
    clients = Client.objects.filter(
        Q(name__icontains=query)
    )
    
    return JsonResponse({
        "clients": [
            {
                'id':client.id,
                'name': client.name,
                'address': client.address,
                'phone': client.phone
            }
            for client in clients
        ]
    })
    
#view para buscar un cliente
def clientView(request):
    id = request.GET.get('id')
    
    client = Client.objects.get(id=id)
    
    return JsonResponse({
        "client": [
            {
                'id':client.id,
                'name': client.name,
                'address': client.address,
                'phone': client.phone
            }
        ]
    })


class SearchSalesByMonthView(ListView):
    template_name = "sales/sales_month.html"
    model = Order
    
    def get_queryset(self):
        query = self.request.GET.get('q')
        object_query = Order.objects.filter(
            Q(createdAt__range=[datetime(2024,3,1), datetime(2024,3,30)])
        )
        return object_query
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["total"] = self.get_total
        context["categories"] = self.get_total_by_category
        return context
    
    def get_total(self):
        total = 0
        for item in self.get_queryset():
            total = total + item.total
        return f'{total:,.2f}'
    
    def get_total_by_category(self):        
        categories = Category.objects.all().order_by('name')
        for category in categories:
            total = 0
 
            for order in self.get_queryset():
                items = OrderDetailSale.objects.filter(order=order.id, product__category=category.id)
                if items:
                    total_list = [x.total for x in items]
                    total += sum(total_list)
                else:
                    continue
            category.total = f'{total:,.2f}'
        return categories
    

class ShopingCartView(TemplateView):
    template_name = "shopping_cart/index.html"
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = OrderDetailSaleForm
        return context
    

def pdfReportSales(request):
    response = HttpResponse(content_type="application/pdf")
    response["Content-Dispositon"] = 'attachment; filename=hello.pdf'
    
    p = canvas.Canvas(response)
    p.setFont("Courier", 28)
    p.drawString(0, 0, "Hola mundo")
    
    p.showPage()
    p.save()
    return response
    


class OrderDetailView(DetailView):
    model = Order
    template_name = "sales/order_detail.html"
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["orders"] = OrderDetailSale.objects.filter(order=context['object'].id)
        print(context) 
        return context
    


class OrderView(TemplateView):
    template_name = "sales/index.html"
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        order = self.object_order()
        context["order"] = order
        context['items'] = Product.objects.all()
        context["form"] = OrderDetailSaleForm
        print(context)
        return context
    
    def object_order(self):
        obj_order = Order(
            number=f'{Order.objects.all().count() + 4090}',
            createdAt=datetime.now(),
            total=0.0,
            client=Client.objects.first(),
            user_id=1
        )
        return obj_order

class OrderDetailSaleCreateView(CreateView):
    model = OrderDetailSale
    form_class = OrderDetailSaleForm
    print(form_class)
    template_name = "sales/order_detail_sale.html"

provider_manager/templates/sales/index.html
{% extends "base/index.html" %}

{% block content_main %}
    <h1>sales index</h1>
    <input type="text", value="{{order.number}}">
    <input type="text", value="{{order.client}}">
    <input type="text", value="{{order.user}}">
    <div>
        <input type="date", value="{{order.createdAt}}">
    </div>
    <div>
        {% include "sales/order_detail_sale.html" %}
    </div>

    <input type="text", value="{{order.total}}">

{% endblock content_main %}

provider_manager/templates/sales/order_detail.html
{% extends "base/index.html" %}

{% block main %}

<div class="container">
    <div class="card">
  <div class="card-header">
    Invoice
    <h2>No. {{object.number}}</h2>
    <strong>{{object.createdAt}}</strong> 
    <span class="float-right"> <strong>Estado:
        {% if object.is_paid %}
            Cancelado
        {% else %}
            Pendiente pago
        {% endif %}
    </strong></span>
  </div>
  <div class="card-body">
    <div class="row mb-4">
        <div class="col-sm-6">
            <h6 class="mb-3">From:</h6>
        <div>
        <strong>Webz Poland</strong>
  </div>
  <div>Madalinskiego 8</div>
  <div>71-101 Szczecin, Poland</div>
  <div>Email: info@webz.com.pl</div>
  <div>Phone: +48 444 666 3333</div>
  </div>
  
  <div class="col-sm-6">
    <h6 class="mb-3">Cliente:</h6>
  <div>
  <strong>consumidor</strong>
  </div>
  <div>Nombres: {{object.client}}</div>
  <div>Dirección: {{object.client.address}}</div>
  <div>Email: </div>
  <div>Phone: +57 {{object.client.phone}}</div>
  </div>
  
  
  
  </div>
  
  <div class="table-responsive-sm">
    <table class="table table-striped">
        <thead>
            <tr>
                <th class="center">#</th>
                <th>Item</th>
                <th>Description</th>
                <th class="center">Qty</th>
                <th class="right">Unit Cost</th>
                <th class="right">Dcto</th>
                <th class="center">Iva</th>
                <th class="right">Total</th>
            </tr>
        </thead>
        <tbody>
            {% for order in orders %}
            <tr>
                <td class="center">{1}</td>
                <td class="left strong">{{order.product.code}}</td>
                <td class="left">{{order.product}}</td>
                <td class="center">{{order.amount}}</td>
                <td class="right">${{order.price}}</td>
                <td class="center">{{order.dto}}</td>
                <td class="center">{{order.product.tax}}</td>
                <td class="right">${{order.total}}</td>
            </tr>
            {% endfor %}
        
        
        </tbody>
    </table>
  </div>
  <div class="row">
  <div class="col-lg-4 col-sm-5">
    <textarea>
        {{object.coments}}
    </textarea>
  </div>
  
  <div class="col-lg-4 col-sm-5 ml-auto">
  <table class="table table-clear">
  <tbody>
  <tr>
  <td class="left">
  <strong>Subtotal</strong>
  </td>
  <td class="right">${{object.total}}</td>
  </tr>
  <tr>
  <td class="left">
  <strong>Discount (20%)</strong>
  </td>
  <td class="right">$0.0</td>
  </tr>
  <tr>
  <td class="left">
   <strong>VAT (19%)</strong>
  </td>
  <td class="right">$0.0</td>
  </tr>
  <tr>
  <td class="left">
  <strong>Total</strong>
  </td>
  <td class="right">
  <strong>${{object.total}}</strong>
  </td>
  </tr>
  </tbody>
  </table>
  
  </div>
  
  </div>
  
  </div>
  </div>
  </div>
{% endblock main %}

provider_manager/templates/sales/order_detail_sale.html
{% block content_order_detail %}
<div class="container mt-3">
    <h2>Striped Rows</h2>
    <p>The .table-striped class adds zebra-stripes to a table:</p>            
    <table class="table table-striped">
      <thead>
        <tr>
          <th>description</th>
          <th>cantidad</th>
          <th>precio unit</th>
          <th>dts</th>
          <th>total</th>
          <th>actions</th>
        </tr>
      </thead>
      <tbody id="id_order">
        <form actions="/sales/orderdetailsale/add/" method="post">
            {% csrf_token %}
            <tr>
                <td>
                  <input class="form-control" name="product" list="datalistOptions" id="id_product" placeholder="Type to search...">
                  <datalist id="datalistOptions">
                      {% for item in items %}
                        <option value="{{item}}">{{item}}</option>
                      {% endfor %}
                  </datalist>                
                </td>
                <td>
                  <input 
                    class="form-control" 
                    name="amount" 
                    type="number" 
                    id="id_amount" 
                    onchange="changeAmount(this)"
                    onkeyup="changeAmount(this)"
                    min="1"
                    value="1"
                  >
                </td>
                <td>
                  <input 
                    class="form-control" 
                    name="price" 
                    type="number" 
                    id="id_price" 
                    onchange="changePrice(this)"
                    onkeyup="changePrice(this)"
                    value="2000"
                    step="1000"
                  >
                </td>
                <td>
                  <input 
                    class="form-control" 
                    name="dto" 
                    type="number" 
                    id="id_dto" 
                    onchange="changeDto(this)"
                    onkeyup="changeDto(this)"
                    min="0"
                    value="0"
                    step="500"
                  >
                </td>
                <td>
                  <p id="p-total">$ 0.0</p>
                </td>
                <td>
                  <input 
                    type="submit" 
                    value="Submit"
                    id="id_submit"
                  >
                </td>
            </tr>
        </form>
      </tbody>
    </table>
  </div>

  {% block content_js %}
    <script>
      const order = []
      const productEl = document.getElementById('id_product')
      const orderEl = document.getElementById('id_order')
      const totalEl = document.getElementById('p-total')
      const amountEl = document.getElementById('id_amount')
      const priceEl = document.getElementById('id_price')
      const dtoEl = document.getElementById('id_dto')

      console.log(orderEl.children[0]);

      document.getElementById('id_submit').addEventListener('click', submitOrderDetailSale)

      const submitOrderDetailSale = ()=>{
        let xhr =  new HMLHttpRequest()

        xhr.open("POST", "/sales/orderdetailsale/add", true)
        
        xhr.setRequestHeader("Content-Type", "application/json")
        xhr.send(JSON.stringify({
          
        }))
        let product = {
          description: productEl.value,
          qty: amountEl.value,
          price: priceEl.value,
          dto: dtoEl.value,
          total: totalEl.textContent
        }

        order.push(product)
        addTableOrder()
        cleanInput(productEl)
      }

      const cleanInput = (element)=>{
        element.value = ''
      }

      const addTableOrder = ()=>{
        //orderEl.innerHTML = ``

        order.forEach(item =>{
          const tr = document.createElement('tr')

          tr.innerHTML = `
            <td>${item.description}</td>
            <td>${item.qty}</td>
            <td>${item.price}</td>
            <td>${item.dto}</td>
            <td>${item.total}</td>
          `

          orderEl.appendChild(tr)
        })
      }

      const calcTotalEl = ()=> {
        totalEl.textContent = `$ ${(amountEl.value * priceEl.value) - dtoEl.value },00`
      }

      const changeAmount = (e)=>{
        amountEl.textContent = e.value
        calcTotalEl()
      }

      const changePrice = (e)=>{
        priceEl.textContent = e.value
        calcTotalEl()
      }

      const changeDto = (e)=>{
        dtoEl.textContent = e.value
        calcTotalEl()
      }
    </script>
  {% endblock content_js %}
    
{% endblock content_order_detail %}

provider_manager/templates/sales/report.html
{% extends "base/index.html" %}

{% block content_main %}
report sales
{% for q in Queryset %}
    {{q}}
{% endfor %}
{% endblock content_main %}

provider_manager/templates/sales/sales_month.html
{% extends "base/index.html" %}

{% load static %}

{% block cdn %}{% endblock cdn %}

{% block title %}
Reporte Ventas por Mes
{% endblock title %}

{% block main%}
<div class="container">
    <div class="card">
        <div class="card-header d-flex justify-content-between bg-white">
            <div>
                name store
            </div>
            <div>
                <p class="h5 fw-bold">Total Ventas</p>
                <h1 class="h3 fw-bold">$ {{ total }}</h1>
            </div>
        </div>
        <div class="card-body">
            <p class="fw-medium text-secondary">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-calendar" viewBox="0 0 16 16">
                    <path d="M3.5 0a.5.5 0 0 1 .5.5V1h8V.5a.5.5 0 0 1 1 0V1h1a2 2 0 0 1 2 2v11a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V3a2 2 0 0 1 2-2h1V.5a.5.5 0 0 1 .5-.5M1 4v10a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V4z"/>
                </svg>
                June 01, 2024 - June 30, 2024
            </p>
            <h1 class="h4 fw-bold">Ventas por categoría</h1>
            <table class="table table-borderless">
                <tbody id="id_table">
                    {% for category in categories %}
                    <tr>
                        <td>{{ category.name }}</td>
                        <td>$ {{ category.total }}</td>
                        <td>+$8000,0</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="card-footer bg-white d-flex justify-content-between">
            <div>
                <p class="fw-medium text-secondary">Total ventas</p>
                <h1 class="h3 fw-bold">$ {{ total }}</h1>
            </div>
            <div>
                <p class="fw-medium text-secondary">Total utilidad</p>
                <h1 class="h3 fw-bold">$750.00</h1>
            </div>
        </div>
    </div>
</div>
{% endblock main %}

{% block javascript %}
<script>
    const table = document.querySelector("#id_table")
    const rows = document.querySelectorAll("tr")

    const comparisonByValue = ()=>{

    }

    rows.forEach(el =>{
        let value = el.cells[1].textContent.replace(/[^0-9.,+\-]/g, '');
        console.log(value)     
    })
</script>
{% endblock javascript %}