provider_manager/invoicing/urls.py
from django.urls import path

from invoicing.views import InvoiceCreateView
from sales.views import SearchClientListView, clientView
from inventory.views import searchProduct, selectProduct

urlpatterns = [
    path('', InvoiceCreateView.as_view(), name='invoice'),
    path('search/client/', SearchClientListView, name='search-client'),
    path('client/', clientView, name='client'),
    path('search/product/', searchProduct, name='search-product'),
    path('product/', selectProduct, name='product'),
]

provider_manager/provider_manager/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', admin.site.urls),
    path('sales/', include('sales.urls')),
    path('collections/', include('inventory.urls')),
    path('providers/', include('provider.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('invoicing/', include('invoicing.urls')),
]

provider_manager/sales/urls.py
from django.urls import path
from sales.views import (
    OrderDetailView, pdfReportSales, ShopingCartView,
    SearchSalesByMonthView
)


urlpatterns = [
    path('invoice/<int:pk>', OrderDetailView.as_view(), name='invoice-detail'),
    path('cart/', ShopingCartView.as_view(), name="cart"),
    path('report/pdf', pdfReportSales, name='report-sales'),
    path('search/', SearchSalesByMonthView.as_view(), name="search-month"),
]

provider_manager/invoicing/models.py
from django.db import models

# Create your models here.

provider_manager/sales/models.py
from django.db import models
from django.urls import reverse
from inventory.models import Product
from django.contrib.auth.models import User
from decimal import Decimal
from django.db.models import Count, Sum

# Create your models here.
class Client(models.Model):
    name = models.CharField(("nombres"), max_length=150)
    num_doc = models.CharField(("cedula"), max_length=20, blank=True, null=True)
    address = models.CharField(("direccion"), max_length=50, blank=True, null=True)
    phone = models.CharField(("telefono"), max_length=50, blank=True, null=True)
    
    class Meta:
        verbose_name = ("Client")
        verbose_name_plural = ("Clients")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("Client_detail", kwargs={"pk": self.pk})

class OrderDetailSale(models.Model):
    product = models.ForeignKey(Product, verbose_name=("products"), on_delete=models.CASCADE)
    amount = models.IntegerField(("cantidad"), default=0)
    price = models.DecimalField(("precio"), max_digits=10, decimal_places=2, default=0.0)
    dto = models.DecimalField(("descuento"), max_digits=10, decimal_places=2, default=0.0)
    total = models.DecimalField(("total"), max_digits=10, decimal_places=2, default=0.0)
    
    class Meta:
        verbose_name = ("OrderDetail")
        verbose_name_plural = ("OrderDetails")

    def __str__(self):
        return self.product.description

    def get_absolute_url(self):
        return reverse("OrderDetail_detail", kwargs={"pk": self.pk})

    def save(self, *args, **kwargs):
        self.total = (self.amount * self.price ) - self.dto    
        return super().save(*args, **kwargs)
    
class Order(models.Model):
    user = models.ForeignKey(User, verbose_name=("vendedor"), on_delete=models.CASCADE)
    client = models.ForeignKey(Client, verbose_name=("clients"), on_delete=models.CASCADE)
    number = models.CharField(("factura"), max_length=50, unique=True)
    orderdetails = models.ManyToManyField(OrderDetailSale, verbose_name=("orderdetailsales"))
    subtotal = models.DecimalField(("subtotal"), max_digits=10, decimal_places=2, default=0.0)
    tax = models.DecimalField(("impuesto"), max_digits=10, decimal_places=2, default=0.0)
    total = models.DecimalField(("total"), max_digits=10, decimal_places=2, default=0.0)
    coments = models.TextField(("observaciones"), blank=True, null=True)
    is_paid = models.BooleanField(("cancelado"), default=False)
    createdAt = models.DateField(("fecha"), auto_now=False)

    class Meta:
        verbose_name = ("Order")
        verbose_name_plural = ("Orders")
        ordering = ("-createdAt",)

    def __str__(self):
        return self.number

    def get_absolute_url(self):
        return reverse("Order_detail", kwargs={"pk": self.pk})
    
    def set_number_bill():
        return f'{4090 + Order.objects.all().count()}'

    def save(self, *args, **kwargs):
        items = OrderDetailSale.objects.filter(order__createdAt=self.createdAt).filter(order__id=self.id)
        print(items)
        if items:
            print(items.filter(order__id=self.id))
            total = items.aggregate(Sum('total'))
            self.total = total['total__sum']
            self.subtotal = self.total / Decimal(1.19)
            self.tax = self.total - self.subtotal
            
        return super().save(*args, **kwargs)


class Utility(models.Model):
    orderdetail = models.ForeignKey(OrderDetailSale, verbose_name=("orderdetailsales"), on_delete=models.CASCADE)
    value = models.DecimalField(("valor"), max_digits=10, decimal_places=2, default=0.0)
    createdAt = models.DateField(auto_now_add=False, blank=True, null=True)
    
    class Meta:
        verbose_name = ("Utility")
        verbose_name_plural = ("Utilities")
        ordering = ("-createdAt",)

    def __str__(self):
        return f'{self.orderdetail}'

    def get_absolute_url(self):
        return reverse("Utility_detail", kwargs={"pk": self.pk})

provider_manager/invoicing/views.py
from django.shortcuts import render

from sales.models import Order, Client

from django.views.generic import CreateView
from django.views.generic import TemplateView

# Create your views here.
class InvoiceCreateView(TemplateView):
    template_name = "invoicing/invoice.html"
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["clients"] = Client.objects.all()
        return context
    

provider_manager/templates/invoicing/invoice.html
{% extends "base/index.html" %}

{% load static %}

{% block title %}
Facturacion
{% endblock title %}

{% block cnd %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/axios/1.6.8/axios.min.js" integrity="sha512-PJa3oQSLWRB7wHZ7GQ/g+qyv6r4mbuhmiDb8BjSFZ8NZ2a42oTtAq5n0ucWAwcQDlikAtkub+tPVCw4np27WCg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
{% endblock cnd %}

{% block css %}{% endblock css %}

{% block main %}
vendedor

informacion de Factura

{% include "client/search.html" %}



{% include "invoicing/order.html" %}

total pedido

notas

opciones(imprimir, guardar)

{% endblock main %}

{% block javascript %}
<script>
    
</script>
{% endblock javascript %}

provider_manager/templates/invoicing/order.html
{% block cnd %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/axios/1.6.8/axios.min.js" integrity="sha512-PJa3oQSLWRB7wHZ7GQ/g+qyv6r4mbuhmiDb8BjSFZ8NZ2a42oTtAq5n0ucWAwcQDlikAtkub+tPVCw4np27WCg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
{% endblock cnd %}

<div>
    <div>
        <input type="text" placeholder="producto", id="id_product" autocomplete="off">
        <ul id="id_items"></ul>
    </div>

    <input type="number" value="0" min="0" id="id_qty" autocomplete="off" onchange="addQty()">
    <span id="id_und">Und</span>
    <input type="number" value="0" id="id_price" autocomplete="off" step="500" onchange="changePrice()">
    <span id="id_total">$ 0.0</span>
    <span onclick="cleanItemOrder()">
        <button>clean</button>
    </span>

</div>

<script>
    const item = document.querySelector('#id_product')
    const items = document.querySelector('#id_items')
    const unit = document.querySelector('#id_und')
    const qty = document.querySelector('#id_qty')
    const total = document.querySelector('#id_total')
    const price = document.querySelector('#id_price')

    //buscar producto
    const getItems = (q)=>{
        axios('search/product/?q=' + q).then(response =>{
            let products = response.data.items

            items.innerHTML = ''

            products.forEach(el =>{
                const li = document.createElement('li')
                li.innerHTML = `
                <li id="${el.id}" onClick="selectItem(${el.code})">${el.description}</li>
                `
                items.appendChild(li)
            })
        })
    }

    item.addEventListener('keyup', (e)=>{
        if(e.target.value != ''){
            getItems(e.target.value)
        }

        items.innerHTML = ''
    })

    //seleccionar producto
    const selectItem = (code)=>{
        axios('product/?q=' + code).then(response =>{
            product = response.data.item[0]
            orderDetail(product)

            items.innerHTML = ''
        })
    }

    // detalle de pedido por prooducto
    const orderDetail = product =>{
        item.value = product.description
        unit.textContent = product.und
        price.value = product.price
        qty.value = 1

        totalItem(product.price, qty.value)
    }

    // cambio de total por cambio de qty
    const totalItem = (qty, price) => total.textContent = qty * price

    // dejar de seleccionar producto para cambio
    const cleanItemOrder = ()=>{
        item.value = ''
        unit.textContent = 'Und'
        price.value = 0.0
        qty.value = 0
        total.textContent = "0.0"
    }

    // accion cambio de qty y cambio en total
    const addQty = () => {
        totalItem(qty.value, price.value)
    }

    qty.addEventListener('keyup', addQty())

    // cambio de precio y cambio de total
    const changePrice = ()=>{
        totalItem(qty.value, price.value)
    }

    price.addEventListener('keyup', changePrice())

</script>