provider_manager/provider_manager/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', admin.site.urls),
    path('sales/', include('sales.urls')),
    path('collections/', include('inventory.urls')),
    path('providers/', include('provider.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('invoicing/', include('invoicing.urls')),
]

provider_manager/sales/urls.py
from django.urls import path
from sales.views import (
    OrderDetailView, pdfReportSales, ShopingCartView,
    SearchSalesByMonthView
)


urlpatterns = [
    path('invoice/<int:pk>', OrderDetailView.as_view(), name='invoice-detail'),
    path('cart/', ShopingCartView.as_view(), name="cart"),
    path('report/pdf', pdfReportSales, name='report-sales'),
    path('search/', SearchSalesByMonthView.as_view(), name="search-month"),
]

provider_manager/sales/forms.py
from django import forms
from sales.models import Order, Client, OrderDetailSale
from django.contrib.auth.models import User

def get_sellerman():
    return User.objects.first().username

def set_number_order():
    num_order = Order.objects.all().count()
    return f'{num_order + 4090}'

def get_bill_not_cancel():
    choices = (('Option 1', 'Option 1'),('Option 2', 'Option 2'),)
    order = Order.objects.filter(is_paid=False)[0]
    choices = ((order.id, order),)
    return choices
    
class OrderForm(forms.ModelForm):
    number = forms.CharField(initial=set_number_order)
    
    class Meta:
        model = Order
        fields = ("user","client","number","orderdetails","createdAt","total","coments")
        # exclude = ("user","client","createdAt","total","coments")

class ClientForm(forms.ModelForm):
    num_doc = forms.CharField(initial='22222222')
    address = forms.CharField(initial='no aplica')
    phone = forms.CharField(initial='000-000-0000')
    
    class Meta:
        model = Client
        fields = ("name","num_doc","address","phone")

class OrderDetailSaleForm(forms.ModelForm):
    class Meta:
        model = OrderDetailSale
        fields = ("product","amount","price","dto")

        widgets = {
            "product": forms.Select(attrs={"class":"form-select form-select-sm"}),
        }

provider_manager/templates/client/search.html
{% block cnd %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/axios/1.6.8/axios.min.js" integrity="sha512-PJa3oQSLWRB7wHZ7GQ/g+qyv6r4mbuhmiDb8BjSFZ8NZ2a42oTtAq5n0ucWAwcQDlikAtkub+tPVCw4np27WCg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
{% endblock cnd %}

<div>
    <div>
        <label for="">Customer</label>
        <input name="q" type="text" placeholder="" id="id_search_customer" autocomplete="off">
    </div>

    <ul id="id_clients"></ul>
</div>



<script>
    const searchCustomer = document.querySelector('#id_search_customer')
    const resClient = document.querySelector("#id_clients")

    //filtrar los clientes
    const getClients = (q)=>{
        axios('search/client/?q=' + q).then(response =>{
            let res = response.data

            resClient.innerHTML = ''

            res.clients.forEach(el =>{
                const li = document.createElement('li')
                li.innerHTML =`
                <li id="id_item_${el.id}" onClick="selectedClient(${el.id})">${el.name}</li>
                ` 
                resClient.appendChild(li)
            })
        })

    }

    //seleccion de un cliente para mostrar sus datos
    const selectedClient = (id)=>{        
        axios('client/?id=' + id).then(response =>{
            let client = response.data.client[0]

            searchCustomer.value = client.name
            resClient.innerHTML = `
            <div>
                <label for="">Address</label>
                <input type="text" value="${client.address}" id="id_address" autocomplete="off">
            </div>
            <div>
                <label for="">Teléfono</label>
                <input type="tel" value="${client.phone}" id="id_phone" autocomplete="off">
            </div>
            `
        })
    }

    // input search
    searchCustomer.addEventListener('keyup', (e)=>{
        if(e.target.value != ''){
            getClients(e.target.value)
        }

        resClient.innerHTML = ''
    })

</script>